version: "3.4"

services:
  migration:
    image: flyway/flyway:latest
    container_name: flyway_migration_solo
    volumes:
     - ./sql:/flyway/sql
     - ./bin:/flyway/bin
    entrypoint: ["bash", "/flyway/bin/wait-for-it.sh", "--timeout=30", "db:1433", "--", "flyway"]      
    command: -url=jdbc:sqlserver://db;database=master -user=sa -password=Asd0123K -mixed=true  migrate 
    depends_on:
      - db
  db:
    image: mcr.microsoft.com/mssql/server
    container_name: mssql1
    environment:
      SA_PASSWORD: "Asd0123K"
      ACCEPT_EULA: "Y"
      MSSQL_AGENT_ENABLED: "true"
    ports:
      - "1700:1433"